// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcA3gqLYfyyQMsMGgApQGeKsx3Zg7n3BM',
    appId: '1:214372786356:web:4df2cd13ae57a372bb37e1',
    messagingSenderId: '214372786356',
    projectId: 'flutter-app-6aa01',
    authDomain: 'flutter-app-6aa01.firebaseapp.com',
    storageBucket: 'flutter-app-6aa01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD7TjDXaZnahTWuMtB-khH1EJo8hzWTFg',
    appId: '1:214372786356:android:2c15f74f61f37d63bb37e1',
    messagingSenderId: '214372786356',
    projectId: 'flutter-app-6aa01',
    storageBucket: 'flutter-app-6aa01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC20ZU4-1AukPwM_bjKgVFtfuWSzTVhCnw',
    appId: '1:214372786356:ios:95073fd1a19964e8bb37e1',
    messagingSenderId: '214372786356',
    projectId: 'flutter-app-6aa01',
    storageBucket: 'flutter-app-6aa01.appspot.com',
    iosClientId: '214372786356-ictcp48o4vibvt9h6lel0ejbqr1oqodi.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp12-2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC20ZU4-1AukPwM_bjKgVFtfuWSzTVhCnw',
    appId: '1:214372786356:ios:11614b735c57c204bb37e1',
    messagingSenderId: '214372786356',
    projectId: 'flutter-app-6aa01',
    storageBucket: 'flutter-app-6aa01.appspot.com',
    iosClientId: '214372786356-ohm8p2egs9n37a99nh7rd9stufeji8s6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );
}
